movies = [
    {"title": "The Shawshank Redemption", "year": 1994},
    {"title": "The Godfather", "year": 1972},
    {"title": "The Dark Knight", "year": 2008},
    {"title": "Pulp Fiction", "year": 1994},
    {"title": "The Lord of the Rings: The Return of the King", "year": 2003},
    {"title": "Schindler's List", "year": 1993},
    {"title": "12 Angry Men", "year": 1957},
    {"title": "Forrest Gump", "year": 1994},
    {"title": "Inception", "year": 2010},
    {"title": "The Matrix", "year": 1999},
    {"title": "Django Unchained", "year": 2012},
    {"title": "The Lives of Others", "year": 2006},
    {"title": "Whiplash", "year": 2014},
    {"title": "The Great Gatsby", "year": 2013},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "A Beautiful Mind", "year": 2001},
    {"title": "The Revenant", "year": 2015},
    {"title": "Jurassic Park", "year": 1993},
    {"title": "The Shining", "year": 1980},
    {"title": "The Social Network", "year": 2010},
    {"title": "The Wolf of Wall Street", "year": 2013},
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004},
    {"title": "Casablanca", "year": 1942},
    {"title": "Amelie", "year": 2001},
    {"title": "Requiem for a Dream", "year": 2000},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Truman Show", "year": 1998},
    {"title": "The Big Lebowski", "year": 1998},
    {"title": "The Terminator", "year": 1984},
    {"title": "The Princess Bride", "year": 1987},
    {"title": "Raiders of the Lost Ark", "year": 1981},
    {"title": "A Clockwork Orange", "year": 1971},
    {"title": "Groundhog Day", "year": 1993},
    {"title": "Blade Runner", "year": 1982},
    {"title": "Gone with the Wind", "year": 1939},
    {"title": "The Graduate", "year": 1967},
    {"title": "The Maltese Falcon", "year": 1941},
]
movies.extend([
    {"title": "The Exorcist", "year": 1973},
    {"title": "Citizen Kane", "year": 1941},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "Star Wars: Episode IV - A New Hope", "year": 1977},
    {"title": "The Wizard of Oz", "year": 1939},
    {"title": "Gone Girl", "year": 2014},
    {"title": "The Silence of the Lambs", "year": 1991},
    {"title": "A Clockwork Orange", "year": 1971},
    {"title": "Goodfellas", "year": 1990},
    {"title": "The Green Mile", "year": 1999},
    {"title": "The Usual Suspects", "year": 1995},
    {"title": "The Good, the Bad and the Ugly", "year": 1966},
    {"title": "The Lion King", "year": 1994},
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004},
    {"title": "Cinema Paradiso", "year": 1988},
    {"title": "The Breakfast Club", "year": 1985},
    {"title": "Inglourious Basterds", "year": 2009},
    {"title": "Casino", "year": 1995},
    {"title": "The Departed", "year": 2006},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "The Shape of Water", "year": 2017},
    {"title": "The Social Network", "year": 2010},
    {"title": "The Big Lebowski", "year": 1998},
    {"title": "The Princess Bride", "year": 1987},
    {"title": "In Bruges", "year": 2008},
    {"title": "La La Land", "year": 2016},
    {"title": "The Sound of Music", "year": 1965},
    {"title": "Black Swan", "year": 2010},
    {"title": "The Shape of Water", "year": 2017},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Inception", "year": 2010},
    {"title": "The Revenant", "year": 2015},
    {"title": "Mad Max: Fury Road", "year": 2015},
    {"title": "The Irishman", "year": 2019},
    {"title": "1917", "year": 2019},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Parasite", "year": 2019},
    {"title": "Joker", "year": 2019},
    {"title": "Avengers: Endgame", "year": 2019},
    {"title": "Toy Story 4", "year": 2019},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018},
    {"title": "Bohemian Rhapsody", "year": 2018},
    {"title": "Black Panther", "year": 2018},
    {"title": "Dunkirk", "year": 2017},
    {"title": "La La Land", "year": 2016},
    {"title": "Moonlight", "year": 2016},
    {"title": "The Martian", "year": 2015},
    {"title": "Birdman", "year": 2014},
    {"title": "Gravity", "year": 2013},
    {"title": "The Artist", "year": 2011},
    {"title": "Slumdog Millionaire", "year": 2008},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Departed", "year": 2006},
    {"title": "Crash", "year": 2004},
    {"title": "Chicago", "year": 2002},
    {"title": "Gladiator", "year": 2000},
    {"title": "The English Patient", "year": 1996},
    {"title": "Braveheart", "year": 1995},
    {"title": "The Piano", "year": 1993},
    {"title": "Unforgiven", "year": 1992},
    {"title": "Dances with Wolves", "year": 1990},
    {"title": "Rain Man", "year": 1988},
    {"title": "Platoon", "year": 1986},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
    {"title": "Hamlet", "year": 1948},
    {"title": "Gentleman's Agreement", "year": 1947},
    {"title": "The Best Years of Our Lives", "year": 1946},
    {"title": "The Lost Weekend", "year": 1945},
    {"title": "Going My Way", "year": 1944},
    {"title": "Casablanca", "year": 1942},
    {"title": "How Green Was My Valley", "year": 1941},
    {"title": "Rebecca", "year": 1940},
    {"title": "Gone with the Wind", "year": 1939},
    {"title": "You Can't Take It with You", "year": 1938},
    {"title": "The Life of Emile Zola", "year": 1937},
    {"title": "The Great Ziegfeld", "year": 1936},
    {"title": "Mutiny on the Bounty", "year": 1935},
    {"title": "It Happened One Night", "year": 1934},
    {"title": "Cavalcade", "year": 1933},
    {"title": "Grand Hotel", "year": 1932},
    {"title": "Cimarron", "year": 1931},
    {"title": "All Quiet on the Western Front", "year": 1930},
    {"title": "Wings", "year": 1927},
    {"title": "The Last Emperor", "year": 1987},
    {"title": "Out of Africa", "year": 1985},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
])
movies.extend([
    {"title": "The Shape of Water", "year": 2017},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Inception", "year": 2010},
    {"title": "The Revenant", "year": 2015},
    {"title": "Mad Max: Fury Road", "year": 2015},
    {"title": "The Irishman", "year": 2019},
    {"title": "1917", "year": 2019},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Parasite", "year": 2019},
    {"title": "Joker", "year": 2019},
    {"title": "Avengers: Endgame", "year": 2019},
    {"title": "Toy Story 4", "year": 2019},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018},
    {"title": "Bohemian Rhapsody", "year": 2018},
    {"title": "Black Panther", "year": 2018},
    {"title": "Dunkirk", "year": 2017},
    {"title": "La La Land", "year": 2016},
    {"title": "Moonlight", "year": 2016},
    {"title": "The Martian", "year": 2015},
    {"title": "Birdman", "year": 2014},
    {"title": "Gravity", "year": 2013},
    {"title": "The Artist", "year": 2011},
    {"title": "Slumdog Millionaire", "year": 2008},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Departed", "year": 2006},
    {"title": "Crash", "year": 2004},
    {"title": "Chicago", "year": 2002},
    {"title": "Gladiator", "year": 2000},
    {"title": "The English Patient", "year": 1996},
    {"title": "Braveheart", "year": 1995},
    {"title": "The Piano", "year": 1993},
    {"title": "Unforgiven", "year": 1992},
    {"title": "Dances with Wolves", "year": 1990},
    {"title": "Rain Man", "year": 1988},
    {"title": "Platoon", "year": 1986},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
    {"title": "The Shape of Water", "year": 2017},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Inception", "year": 2010},
    {"title": "The Revenant", "year": 2015},
    {"title": "Mad Max: Fury Road", "year": 2015},
    {"title": "The Irishman", "year": 2019},
    {"title": "1917", "year": 2019},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Parasite", "year": 2019},
    {"title": "Joker", "year": 2019},
    {"title": "Avengers: Endgame", "year": 2019},
    {"title": "Toy Story 4", "year": 2019},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018},
    {"title": "Bohemian Rhapsody", "year": 2018},
    {"title": "Black Panther", "year": 2018},
    {"title": "Dunkirk", "year": 2017},
    {"title": "La La Land", "year": 2016},
    {"title": "Moonlight", "year": 2016},
    {"title": "The Martian", "year": 2015},
    {"title": "Birdman", "year": 2014},
    {"title": "Gravity", "year": 2013},
    {"title": "The Artist", "year": 2011},
    {"title": "Slumdog Millionaire", "year": 2008},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Departed", "year": 2006},
    {"title": "Crash", "year": 2004},
    {"title": "Chicago", "year": 2002},
    {"title": "Gladiator", "year": 2000},
    {"title": "The English Patient", "year": 1996},
    {"title": "Braveheart", "year": 1995},
    {"title": "The Piano", "year": 1993},
    {"title": "Unforgiven", "year": 1992},
    {"title": "Dances with Wolves", "year": 1990},
    {"title": "Rain Man", "year": 1988},
    {"title": "Platoon", "year": 1986},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
    {"title": "The Shape of Water", "year": 2017},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Inception", "year": 2010},
    {"title": "The Revenant", "year": 2015},
    {"title": "Mad Max: Fury Road", "year": 2015},
    {"title": "The Irishman", "year": 2019},
    {"title": "1917", "year": 2019},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Parasite", "year": 2019},
    {"title": "Joker", "year": 2019},
    {"title": "Avengers: Endgame", "year": 2019},
    {"title": "Toy Story 4", "year": 2019},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018},
    {"title": "Bohemian Rhapsody", "year": 2018},
    {"title": "Black Panther", "year": 2018},
    {"title": "Dunkirk", "year": 2017},
    {"title": "La La Land", "year": 2016},
    {"title": "Moonlight", "year": 2016},
    {"title": "The Martian", "year": 2015},
    {"title": "Birdman", "year": 2014},
    {"title": "Gravity", "year": 2013},
    {"title": "The Artist", "year": 2011},
    {"title": "Slumdog Millionaire", "year": 2008},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Departed", "year": 2006},
    {"title": "Crash", "year": 2004},
    {"title": "Chicago", "year": 2002},
    {"title": "Gladiator", "year": 2000},
    {"title": "The English Patient", "year": 1996},
    {"title": "Braveheart", "year": 1995},
    {"title": "The Piano", "year": 1993},
    {"title": "Unforgiven", "year": 1992},
    {"title": "Dances with Wolves", "year": 1990},
    {"title": "Rain Man", "year": 1988},
    {"title": "Platoon", "year": 1986},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
    {"title": "Hamlet", "year": 1948},
    {"title": "Gentleman's Agreement", "year": 1947},
    {"title": "The Best Years of Our Lives", "year": 1946},
    {"title": "The Lost Weekend", "year": 1945},
    {"title": "Going My Way", "year": 1944},
    {"title": "Casablanca", "year": 1942},
    {"title": "How Green Was My Valley", "year": 1941},
    {"title": "Rebecca", "year": 1940},
    {"title": "Gone with the Wind", "year": 1939},
    {"title": "You Can't Take It with You", "year": 1938},
    {"title": "The Life of Emile Zola", "year": 1937},
    {"title": "The Great Ziegfeld", "year": 1936},
    {"title": "Mutiny on the Bounty", "year": 1935},
    {"title": "It Happened One Night", "year": 1934},
    {"title": "Cavalcade", "year": 1933},
    {"title": "Grand Hotel", "year": 1932},
    {"title": "Cimarron", "year": 1931},
    {"title": "All Quiet on the Western Front", "year": 1930},
    {"title": "Wings", "year": 1927},
    {"title": "The Last Emperor", "year": 1987},
])

movies.extend([
    {"title": "Gone with the Wind", "year": 1939},
    {"title": "You Can't Take It with You", "year": 1938},
    {"title": "The Life of Emile Zola", "year": 1937},
    {"title": "The Great Ziegfeld", "year": 1936},
    {"title": "Mutiny on the Bounty", "year": 1935},
    {"title": "It Happened One Night", "year": 1934},
    {"title": "Cavalcade", "year": 1933},
    {"title": "Grand Hotel", "year": 1932},
    {"title": "Cimarron", "year": 1931},
    {"title": "All Quiet on the Western Front", "year": 1930},
    {"title": "Wings", "year": 1927},
    {"title": "The Last Emperor", "year": 1987},
    {"title": "Out of Africa", "year": 1985},
    {"title": "Amadeus", "year": 1984},
    {"title": "Terms of Endearment", "year": 1983},
    {"title": "Chariots of Fire", "year": 1981},
    {"title": "Ordinary People", "year": 1980},
    {"title": "Kramer vs. Kramer", "year": 1979},
    {"title": "The Deer Hunter", "year": 1978},
    {"title": "Annie Hall", "year": 1977},
    {"title": "Rocky", "year": 1976},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975},
    {"title": "The Godfather: Part II", "year": 1974},
    {"title": "The Sting", "year": 1973},
    {"title": "The French Connection", "year": 1971},
    {"title": "Midnight Cowboy", "year": 1969},
    {"title": "Oliver!", "year": 1968},
    {"title": "In the Heat of the Night", "year": 1967},
    {"title": "A Man for All Seasons", "year": 1966},
    {"title": "My Fair Lady", "year": 1964},
    {"title": "Tom Jones", "year": 1963},
    {"title": "Lawrence of Arabia", "year": 1962},
    {"title": "The Apartment", "year": 1960},
    {"title": "Ben-Hur", "year": 1959},
    {"title": "Gigi", "year": 1958},
    {"title": "The Bridge on the River Kwai", "year": 1957},
    {"title": "Around the World in 80 Days", "year": 1956},
    {"title": "Marty", "year": 1955},
    {"title": "On the Waterfront", "year": 1954},
    {"title": "From Here to Eternity", "year": 1953},
    {"title": "The Greatest Show on Earth", "year": 1952},
    {"title": "An American in Paris", "year": 1951},
    {"title": "All About Eve", "year": 1950},
    {"title": "Hamlet", "year": 1948},
    {"title": "Gentleman's Agreement", "year": 1947},
    {"title": "The Best Years of Our Lives", "year": 1946},
    {"title": "The Lost Weekend", "year": 1945},
    {"title": "Going My Way", "year": 1944},
    {"title": "Casablanca", "year": 1942},
    {"title": "How Green Was My Valley", "year": 1941},
    {"title": "Rebecca", "year": 1940},
])

def make_movies_unique_and_write_to_file(movie_list, output_file):
    unique_movies = []
    seen_movies = set()

    for movie in movie_list:
        # Convert the movie information to a tuple for easier comparison
        movie_tuple = (movie["title"], movie["year"])

        # Check if the movie is already in the set
        if movie_tuple not in seen_movies:
            seen_movies.add(movie_tuple)
            unique_movies.append(movie)

    # Write the unique movie list to a Python file
    with open(output_file, 'w') as file:
        file.write("unique_movies = [\n")
        for movie in unique_movies:
            file.write(f'    {{"title": "{movie["title"]}", "year": {movie["year"]}}},\n')
        file.write("]\n")

output_file_name = 'unique_movies_list.py'
make_movies_unique_and_write_to_file(movies, output_file_name)