"""
Author: Fadi Nimer
Date: November 20, 2023
Description:    This script populates EntertainmentDB with all output
                .sql files generated by <movie_tv_dml_generator.py>.
"""

import os
import mysql.connector
from ... import config

try:
    connection = mysql.connector.connect(**config.db_config)
    cursor = connection.cursor()
    print("Connected to the database")

    # SQL files directory
    sql_files_directory = '../../Queries/Movie_TV-DML/'

    for filename in os.listdir(sql_files_directory):
        if filename.endswith(".sql"):
            file_path = os.path.join(sql_files_directory, filename)

            with open(file_path, 'r', encoding='utf-8') as sql_file:
                queries = sql_file.read().split(';')

                for query in queries:
                    try:
                        cursor.execute(query)
                        print(f"Executed query: {query}")

                        # Ignore results
                        for _ in cursor.fetchall():
                            pass

                    except mysql.connector.Error as e:
                        print(f"Error executing query: {query}\nError: {e}")

            connection.commit()
            print("Changes committed to the database")

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("Connection closed")
